import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import agent from "../utils/agent";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Template Example app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Main page</h1>
        <Link href="/clientsidefetch" passHref>
          <a>Client Side fetch</a>
        </Link>
        <Link href="/serversidefetch" passHref>
          <a>Server Side fetch</a>
        </Link>

        <button
          onClick={() =>
            agent()
              .logout()
              .then(() => router.push("/login"))
          }
        >
          Logout
        </button>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {},
  };
}
